name: osscompliance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: License compliance check
      uses: mikaelvesavuori/license-compliance-action@v1.0.2
